name: Build for Linux
on: [push]
jobs:
  Build-Linux-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install zstd
        run: sudo apt-get install libzstd-dev
      - name: Build
        run: make; ls -l
      - name: Test Periculosum
        run: make test
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Check Go version
        run: go version
      - name: Test Checker
        run: cd goperic; go test -v
      - name: Pack release
        run: bash release_linux.sh
#        run: tar cfvz periculosum_linux64.tgz periculosum checker LICENSE README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: periculosum_linux64.zip