make: Build for Windows
on:
  push:
    branches: [ main ]
jobs:
  Build-Windows-Release:
    name: Build & Test & Pack
    runs-on: windows-latest
    steps:
    # every step must define a `uses` or `run` key
      - run: git config --global core.autocrlf input
        name: Config Git
      - name: Check out repository code
      - uses: actions/checkout@v3
      - uses: cygwin/cygwin-install-action@master
        name: Install Cygwin
        with:
          packages: >-
            base
            make
            autoreconf
            libtool
            autoconf
            automake
            gcc-g++
            zip
      - name: Build
        run: bash -c make; ls -l
      - name: Test Periculosum
        run: make test
        uses: actions/setup-go@v2
        name: Setup Go
      - name: Check Go version
        run: go version
      - name: Test Checker
        run: cd goperic; go test -v
      - name: Pack release
        run: base release_windows.sh
      - name: Release for Windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release_windows64.zip