on:
  push:
    branches: [ main ]
jobs:
  Build-Windows-Release:
    runs-on: windows-latest
    steps:
    # every step must define a `uses` or `run` key
      - run: git config --global core.autocrlf input
        name: Config Git
      - name: Check out repository code
      - uses: actions/checkout@v3
