name: Build for Windows
on: [push]
#on:
#  push:
#    branches: [ main ]
jobs:
  Build-Windows-Release:
    name: Build & Test & Pack
    runs-on: windows-2019
# windows-latest
    steps:
      - run: git config --global core.autocrlf input
        name: Config Git
      - uses: actions/checkout@v3
        name: Check out repository code
#      - uses: cygwin/cygwin-install-action@master
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: >-
            base
            make
            autoreconf
            libtool
            autoconf
            automake
            gcc-g++
            zip
            xxd
      - name: Build
        run: bash -c make
      - name: Test Periculosum
        run: make test
      - uses: actions/setup-go@v2
        name: Setup Go
      - name: Check Go version
        run: go version
      - name: Test Checker
        run: cd goperic; go test -v
      - name: Pack release
        run: base release_windows.sh
      - name: Release for Windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release_windows64.zip