name: Build for Windows
on: [push]
#on:
#  push:
#    branches: [ main ]
jobs:
  Build-Windows-Release:
    name: Build & Test & Pack
    runs-on: windows-2022
# windows-latest
    steps:
      - run: git config --global core.autocrlf input
        name: Config Git
      - uses: actions/checkout@v3
        name: Check out repository code
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            make
            autoconf
            automake
            libtool
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-libgnurx
            mingw-w64-x86_64-go
            zip
            vim
      - name: Build
        shell: msys2 {0}
        run: make
      - name: Test Periculosum
        shell: msys2 {0}
        run: make test

      - name: Locate objdump
        shell: pwsh
        run: |
          Get-ChildItem C:\msys64 -Recurse objdump.exe

      - name: Show DLL dependencies
        shell: pwsh
        run: |
          & "C:\msys64\mingw64\bin\objdump.exe" -p .\periculosum.exe | Select-String "DLL Name"

      - name: Smoke test without MinGW
        shell: pwsh
        run: |
          mkdir clean

          Copy-Item .\periculosum.exe clean\

          cd clean

          $env:PATH = "C:\Windows\System32;C:\Windows"

          try {
            .\periculosum.exe 2>&1 | Out-Host

            Write-Host "Exit code: $LASTEXITCODE"

            if ($LASTEXITCODE -ne 0) {
              throw "Application exited with error"
            }
          }
          catch {
            Write-Host $_
            throw
          }
      - name: Check Go version
        shell: msys2 {0}
        run: go version
      - name: Test Checker
        shell: msys2 {0}
        run: cd goperic; go test -v
      - name: Pack release
        shell: msys2 {0}
        run: bash release_windows.sh
      - name: Release for Windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: periculosum_windows64.zip