on: [push]
jobs:
  Build-Linux-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Test
        run: make test
